FROM ghcr.io/mlflow/mlflow:v2.15.1

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends libexpat1 && \
    rm -rf /var/lib/apt/lists/*
# Installation du pilote PostgreSQL indispensable
RUN pip install psycopg2-binary