# Remplacez v2.15.1 par une version récente (ex: v2.19.0) ou utilisez latest
FROM ghcr.io/mlflow/mlflow:latest

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends libexpat1 && \
    rm -rf /var/lib/apt/lists/*
RUN pip install psycopg2-binary